### ISSUE TITLE
Configure base backend project to be a proper spring web application

### ISSUE THREAD

**Issue by Sewq** [javastartpl/sasiedzki-bazar-umiejetnosci#6]
For now there is only a boilerplate project with some needed dependencies. One have to change the pom file to use proper spring dependencies to develop a web application.

**Comment by Sewq** [comment]
Or even use spring boot to create a new one ; )

**Comment by kstefanczyk** [comment]
I'm working on that. Rather will use your pom. Keep you updated! :)
